process.env.URL = 'https://vercel.com/careers?department=Engineering'
process.env.REGION = 'United States'
process.env.BASE_CLASS_NAME = 'careers_ul'
process.env.TITLE = 'Engineer'
process.env.FILE_PATH = './jobs.json'
